language: python
python:
  - "3.5"
  - "3.6"

# Current workaround to test on Python 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

notifications:
    email: false

# Install packages
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install .  # Install BirdSongToolbox
  - pip install pytest-cov
  - pip install codecov

script:
  - pytest --cov=./

after_success:
  - codecov --token=<a0c9bce2-2f60-4c11-aaa3-d2372a5f7e4b>

