language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# Current workaround to test on Python 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

notifications:
    email: false

# Install packages
install:
  - pip install -r requirements.txt
#  - pip install pytest-cov
#  - pip install codecov
#  - pip install .  # This has somethihng to do with Testing with PyPi

script:
  - pytest
#  - pytest --cov=BirdSongToolbox

#after_success:
#  - coveralls

